name: Build binaries

on:
  push:
    tags:
    - "v*"
  workflow_dispatch:


jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: "1.22"

    # dependencies for fyne on linux
    - name: Install Linux deps
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt update
        sudo apt install -y gcc libgl1-mesa-dev xorg-dev

    - name: Download dependencies
      run: go mod tidy

    - name: Build
      run: |
        go build -ldflags "-H=windowsgui" -o app

    - name: Rename binary
      run: |
        if [ "${{ matrix.os }}" = "windows-latest" ]; then mv app app.exe; fi
      shell: bash

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-${{ matrix.os }}
        path: |
          app
          app.exe
